// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"infogpt/internal/conf"
	"infogpt/internal/server"
	"infogpt/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, adminConf *conf.Admin, logger log.Logger) (*kratos.App, func(), error) {
	adminService, err := service.NewAdminService(adminConf, logger)
	if err != nil {
		return nil, func(){}, err
	}
	
	grpcServer := server.NewGRPCServer(confServer, adminService, logger)
	httpServer := server.NewHTTPServer(confServer, adminService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {}, nil
}
