server:
  http:
    addr: 0.0.0.0:6060
    timeout: 300s
  grpc:
    addr: 0.0.0.0:6061
    timeout: 2s
admin:
  openai_api_key: ""
  chatgpt_access_token: ""
  chatgpt_puid: ""
  proxy_url: ""
  # gin 路由的ratelimit配置，以IP作为key
  # "5-S" 限制 5 req/s 秒
  # "5-M" 限制 5 req/m 分钟
  # "5-H" 限制 5 req/h 小时
  # "5-D" 限制 5 req/d 天
  gin_ratelimit: "20-D"
  telegram_token: ""
  telegram_ratelimit: "20-D"
  official_account:
    app_id: ""
    app_secret: ""
    token: ""
    encoding_aes_key: ""
    auto_replay:
      "001": "infogpt infogpt1"
