server:
  http:
    addr: 0.0.0.0:8000
    timeout: 15s
    proxy_url: "http://127.0.0.1:1082"
    proxy_timeout: 15s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 2s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
openai:
  api_key: ""
  proxy_url: ""
