server:
  http:
    addr: 0.0.0.0:6060
    timeout: 300s
  grpc:
    addr: 0.0.0.0:6061
    timeout: 2s
admin:
  openai_api_key: ""
  proxy_url: ""
  # gin 路由的ratelimit配置，以IP作为key
  # "5-S" 限制 5 req/s 秒
  # "5-M" 限制 5 req/m 分钟
  # "5-H" 限制 5 req/h 小时
  # "5-D" 限制 5 req/d 天
  gin_ratelimit: "20-D"
  telegram:
    token: ""
    # 机器人的请求限制，原则上应该比 user_ratelimit 大，为空则不进行限制
    ratelimit: ""
    # 每个用户的请求限制，为空则不进行限制
    user_ratelimit: "20-D"
  wechat:
    app_id: ""
    app_secret: ""
    token: ""
    encoding_aes_key: ""
    auto_replay:
      "001": "infogpt infogpt1"
