server:
  http:
    addr: 0.0.0.0:6060
    timeout: 300s
  grpc:
    addr: 0.0.0.0:6061
    timeout: 2s
admin:
  openai_api_key: ""
  chatgpt_access_token: ""
  chatgpt_puid: ""
  proxy_url: ""
  telegram_token: ""
